### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by smpentecost** [AF-Tools/bullet-buddy#3]
Hey Nick. Your tool has gotten some good feedback on the AF subreddit (https://www.reddit.com/r/AirForce/comments/ppi77k/to_the_guy_that_made_the_af_bullet_shaping_webpage/). I currently host some other bullet editing apps on www.lightningwithinfive.com and thought I'd reach out and see if you're okay with me hosting your app there as well. If so, just let me know and add an open source license to your repo.

**Comment by NicholasSchweikart** [comment]
working now!

**Comment by NicholasSchweikart** [comment]
I think its GTG. Lemme know if it needs to be copied into all the src code too...
